version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: sambo_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-sambo_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sambo_password}
      POSTGRES_DB: ${POSTGRES_DB:-sambo_academy}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sambo_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: sambo_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://sambo_user:sambo_password@db:5432/sambo_academy
      SECRET_KEY: ${SECRET_KEY:-your-secret-key-change-in-production}
      ALGORITHM: ${ALGORITHM:-HS256}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-10080}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
