"""Add default_subscription_type to groups

Revision ID: 0c9a9b94f082
Revises: 74957a18dadc
Create Date: 2025-10-05 22:05:18.537666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c9a9b94f082'
down_revision = '74957a18dadc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_settings_key', table_name='settings')
    op.drop_table('settings')
    op.drop_index('idx_attendances_session_date', table_name='attendances')
    op.create_index(op.f('ix_attendances_session_date'), 'attendances', ['session_date'], unique=False)
    op.add_column('groups', sa.Column('default_subscription_type', sa.String(length=20), nullable=True, comment='Тип абонемента по умолчанию для группы (8_sessions или 12_sessions)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'default_subscription_type')
    op.drop_index(op.f('ix_attendances_session_date'), table_name='attendances')
    op.create_index('idx_attendances_session_date', 'attendances', ['session_date'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_system', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='settings_pkey')
    )
    op.create_index('ix_settings_key', 'settings', ['key'], unique=True)
    # ### end Alembic commands ###
