"""Add skill_level to groups

Revision ID: 74957a18dadc
Revises: f71e224447a7
Create Date: 2025-10-05 16:56:12.120514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74957a18dadc'
down_revision = 'f71e224447a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('skill_level', sa.Enum('BEGINNER', 'EXPERIENCED', name='skill_level'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'skill_level')
    # ### end Alembic commands ###
