"""Update groups model with age_group and schedule_type

Revision ID: f71e224447a7
Revises: 
Create Date: 2025-10-05 16:42:15.001216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f71e224447a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('age_group', sa.Enum('SENIOR', 'JUNIOR', name='age_group'), nullable=False))
    op.add_column('groups', sa.Column('schedule_type', sa.Enum('MON_WED_FRI', 'TUE_THU', name='schedule_type'), nullable=False))
    op.drop_column('groups', 'group_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('group_type', postgresql.ENUM('SENIOR', 'JUNIOR', name='group_type'), autoincrement=False, nullable=False))
    op.drop_column('groups', 'schedule_type')
    op.drop_column('groups', 'age_group')
    # ### end Alembic commands ###
